const User = require("./models/user");

/* 
User.findByID(1, (error, user) => {
    if (error) {
        console.log(error);
        return;
    };
    console.log(user);
});
 */

/* 
User.findAll((error, users) => {
    if (error) {
        console.log(error);
        return;
    }
    console.log(users);
});
 */

/* 
// We don't need to provide the id because it is generated by the database. 
const user = {
    username: "julius",
    full_name: "Julius",
    bio: "Software engineer at Boogle",
    date_of_birth: "2001-10-16"
}; 

User.insert(user, (error, userID) => {
    if (error) {
        console.log(error);
        return;
    };
    console.log(userID);
});
 */

/* 
const editedUser = {
    full_name: "Julius Lim",
    username: "julius",
    bio: "Software engineer at Boogle",
    date_of_birth: "2001-10-15"
};

// provide the user id of the user with full_name "Julius" 
// it may not be 5 for you 
User.edit(5, editedUser, (error) => {
    if (error) {
        console.log(error);
        return;
    };
});
 */

/* 
// Add friend
User.addFriend(1, 3, (error) => {
    if (error) {
        console.log('Error adding friend:', error);
    } else {
        console.log('Friend added successfully');
    }
});

// Remove friend
User.removeFriend(1, 3, (error) => {
    if (error) {
        console.log('Error removing friend:', error);
    } else {
        console.log('Friend removed successfully');
    }
});

// Show friends
User.showFriends(1, (error, friends) => {
    if (error) {
        console.log('Error retrieving friends:', error);
    } else {
        console.log('Friends:', friends);
    }
});
 */

const Post = require('./models/post.js');

/* 
// Find posts by user ID
Post.findByUserID(1, (error, posts) => {
    if (error) {
        console.log('Error finding posts by user ID:', error);
    } else {
        console.log('Posts found by user ID:', posts);
    }
});
 */

/* 
// Find post by ID
Post.findByID(1, (error, post) => {
    if (error) {
        console.log('Error finding post by ID:', error);
    } else {
        console.log('Post found by ID:', post);
    }
});
 */

/* 
// Find all posts
Post.findAll((error, posts) => {
    if (error) {
        console.log('Error finding all posts:', error);
    } else {
        console.log('All posts:', posts);
    }
});
 */

/* 
// Insert a new post
const newPost = {
    text_body: 'New post',
    fk_poster_id: 1,
};
Post.insert(newPost, (error, postID) => {
    if (error) {
        console.log('Error inserting post:', error);
    } else {
        console.log('Post inserted with ID:', postID);
    }
});
 */

/* 
// Edit a post
const editedPost = {
    text_body: 'Edited post',
};
Post.edit(11, editedPost, (error) => {
    if (error) {
        console.log('Error editing post:', error);
    } else {
        console.log('Post edited successfully');
    }
});
 */

/* 
// Delete a post
Post.delete(11, (error) => {
    if (error) {
        console.log('Error deleting post:', error);
    } else {
        console.log('Post deleted successfully');
    }
});
 */

/* 
// Like a post
Post.like(1, 1, (error) => {
    if (error) {
        console.log('Error liking post:', error);
    } else {
        console.log('Post liked successfully');
    }
});
 */

/* 
// Unlike a post
Post.unlike(1, 1, (error) => {
    if (error) {
        console.log('Error unliking post:', error);
    } else {
        console.log('Post unliked successfully');
    }
});
 */

/* 
// Find likers of a post
Post.findLikers(1, (error, likers) => {
    if (error) {
        console.log('Error finding likers:', error);
    } else {
        console.log('Likers:', likers);
    }
});
 */

const app = require("./controller/app");

const PORT = 3000;
app.listen(PORT, () => {
    console.log(`Server started on port ${PORT}`);
});

